Update update-hustoj

diff --git a/trunk/install/update-hustoj b/trunk/install/update-hustoj
--- a/trunk/install/update-hustoj
+++ b/trunk/install/update-hustoj
@@ -2,7 +2,12 @@
 cd /home/judge/git
 git pull
 
-svn up /home/judge/src
+while ! svn up /home/judge/src
+do
+  echo "Subversion update from github.com failed , retry in 5 seconds ..."
+  sleep 5s
+done
+
 cd /home/judge/src/core
 pkill -9 judged
 bash make.sh
